apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: abanoubfathy/expiration
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:4222
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
