name: auth-service-deployment

on:
  push:
    branches: main
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cd auth && docker build -t $DOCKER_USER_NAME/auth .
      - run: docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
      - run: docker push $DOCKER_USER_NAME/auth

env:
  DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
