name: auth-service-deployment

on:
  push:
    branches: main
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: build an image
        run: cd auth && docker build -t ${{ secrets.DOCKER_USER_NAME }}/auth .

      - name: login to dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: push a new image to dockerhub
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/auth
